language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt 
  - pip install coverage
  - pip install coveralls
script:
  - python setup.py install
  - psiturk-setup-example
  - coverage run --source=psiturk setup.py test
after_success: coveralls
